$browser = firefox
$editor = code

$kbTerminal = Super, Q
$workspaceSwipeFingers = 3
$kbCloseWindow = Super+Shift, X

windowrulev = float,class:^(mypipes)$
windowrulev = float,class:^(mybtop)$
windowrulev = float,class:^(mycava)$
windowrulev = noinitialfocus,class:^(mypipes|mybtop|mycava)$
windowrulev = stayfocused,class:^(mypipes|mybtop|mycava)$